---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 了解BlueXP  工作负载工厂中工作负载的最新变化。 
---
= BlueXP  工作负载出厂时的最新变更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解BlueXP  工作负载工厂中工作负载的最新变化。



== 2025年6月30日



=== 数据库工作负载



==== BlueXP 工作负载工厂通知服务支持

BlueXP 工作负载工厂通知服务支持工作负载工厂向 BlueXP 警报服务或 Amazon SNS 主题发送通知。发送到 BlueXP 警报的通知会显示在 BlueXP 警报面板中。当工作负载工厂向 Amazon SNS 主题发布通知时，该主题的订阅者（例如人员或其他应用程序）会在为该主题配置的终端节点上收到通知（例如电子邮件或短信）。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作负载工厂通知"^]

工作负载工厂为数据库提供以下通知：

* 结构完善的报告
* 主机部署
* 保护




==== 用于注册实例的入门增强功能

数据库工作负载工厂改进了在 Amazon FSx for NetApp ONTAP 存储上运行的实例的注册流程。现在，您可以批量选择实例进行注册。实例注册完成后，您可以在工作负载工厂控制台中创建和管理数据库主机资源。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["实例管理"]



==== Microsoft Multipath I/O 超时设置的分析与修复

数据库主机实例的架构完善状态现在包含对 Microsoft 多路径 I/O (MPIO) 超时设置的分析和修复。将 MPIO 超时设置为 60 秒可确保 FSx for ONTAP 存储故障转移期间的连接性和稳定性。如果 MPIO 设置未正确设置，工作负载工厂将提供修复程序，将 MPIO 超时值设置为 60 秒。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在工作负载工厂中实现架构良好的数据库配置"]



==== 主机库存中的图形增强功能

在主机清单屏幕中，各种资源利用率图表（例如吞吐量和 IOPS）现在显示 7 天的数据，以便您可以更高效地从工作负载工厂控制台监控 SQL 节点的性能。从 SQL 节点收集的性能指标将保存在 Amazon CloudWatch 中，可用于 Logs Insights 或与您环境中的其他分析服务集成。

从主机清单中的实例和数据库选项卡中，我们增强了主机保护的描述和可视化。



==== 工作负载工厂中对 Windows 身份验证的支持

现在，工作负载工厂支持使用 Windows 身份验证用户的 SQL Server 身份验证来注册主机实例并受益于主机管理功能。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["在数据库的工作负载工厂中注册主机实例"]



== 2025年6月29日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== BlueXP 工作负载工厂通知服务支持

BlueXP 工作负载工厂通知服务支持工作负载工厂向 BlueXP 警报服务或 Amazon SNS 主题发送通知。发送到 BlueXP 警报的通知会显示在 BlueXP 警报面板中。当工作负载工厂向 Amazon SNS 主题发布通知时，该主题的订阅者（例如人员或其他应用程序）会在为该主题配置的终端节点上收到通知（例如电子邮件或短信）。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作负载工厂通知"^]



==== 存储仪表板增强功能

工作负载工厂控制台中的存储控制面板新增了节省机会卡片。控制面板顶部的卡片显示在 Amazon Elastic Block Store (EBS)、Amazon FSx for Windows File Server 和 Amazon Elastic File Systems (EFS) 上运行的存储环境的节省机会数量。控制面板底部新增了三张卡片，按 Amazon 存储服务（EBS、FSx for Windows File Server 和 EFS）显示节省机会。您可以从所有卡片中更详细地了解节省机会。

通过 FSx for ONTAP 保护覆盖率卡和复制关系健康卡，您可以调查 FSx for ONTAP 文件系统中是否存在任何部分受保护的卷，以及调查复制关系的问题。在这两种情况下，您都可以采取措施来解决问题。



==== 音量选项卡增强功能

工作负载工厂控制台中的“卷”选项卡已得到增强，可提供更全面的 FSx for ONTAP 文件系统视图。增强功能包括新增 SSD 容量、容量池以及 NetApp 自主勒索软件防护 AI (ARP/AI) 卡。这些卡汇总了文件系统中所有卷的容量利用率和 ARP/AI 防护功能。



==== 支持适用于NetApp ONTAP文件系统的第二代Amazon FSx

工作负载工厂现已支持第二代 Amazon FSx for NetApp ONTAP 文件系统。您可以在工作负载工厂控制台中创建、管理和监控第二代文件系统。所有新的商业区域均受支持。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["在工作负载工厂中创建第二代文件系统"]



==== FlexVol 卷支持重新平衡卷容量

FlexVol 卷可在工作负载工厂控制台中发现。您可以检查 FlexVol 卷的平衡情况，并在新文件的添加和文件增长导致不平衡时重新平衡 FlexVol 卷以重新分配容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["重新平衡 FlexVol 卷的容量"]



==== 术语更新

在工作负载工厂控制台中，“自主勒索软件防护”(ARP) 一词已更新为“带 AI 的 NetApp 自主勒索软件防护”(ARP/AI)。



==== 新卷默认启用 ARP/AI

在工作负载工厂控制台中创建新卷时，如果文件系统具有 ARP/AI 策略，则 NetApp 自主勒索软件防护 AI (ARP/AI) 将默认启用。这意味着该卷将使用 AI 驱动的检测和响应功能自动防御勒索软件攻击。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["在工作负载工厂中创建卷"]



==== 对不可变文件的复制支持

工作负载工厂支持将不可变卷从一个 FSx for ONTAP 系统复制到另一个 FSx for ONTAP 文件系统，以保护关键数据免遭意外删除或勒索软件等恶意攻击。目标卷及其主机文件系统将处于不可变状态（即锁定状态），并且在保留期结束之前，目标文件系统中的任何数据都无法修改或删除。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["了解如何创建复制关系"]



==== 在链接创建期间管理 IAM 执行角色和权限

现在，您可以在工作负载工厂控制台中创建链接，从而管理 IAM 执行角色及其附加的权限策略。链接会在您的工作负载工厂账户与一个或多个 FSx for ONTAP 文件系统之间建立连接。您可以通过两种方式分配 IAM 执行角色和链接权限：自动分配或用户分配。在工作负载工厂中管理执行角色及其附加的权限策略意味着您无需再使用第三方代码。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["使用Lamba链接连接到FSx for ONTAP文件系统"]



=== VMware工作负载



==== 引入对 Amazon Elastic VMWare Service 的迁移顾问支持

BlueXP VMware 工作负载工厂现已支持 Amazon Elastic VMware Service。您可以使用迁移顾问快速将本地 VMware 工作负载迁移到 Amazon Elastic VMware Service，从而优化成本并更好地控制您的 VMware 环境，而无需重构或重新构建应用程序平台。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["使用迁移顾问为 Amazon EVS 创建部署计划"]



=== GenAI工作负载



==== 支持托管在通用 NFS/SMB 文件系统上的数据源

您现在可以从通用 SMB 或 NFS 共享添加数据源。这使您能够包含存储在 Amazon FSx for NetApp ONTAP 以外的文件系统托管的卷上的文件。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["向知识库添加数据源"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["向连接器添加数据源"]



=== 设置和管理



==== 更新数据库的权限

现在，数据库在只读模式下具有以下权限：  `cloudwatch:GetMetricData` 。

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



==== BlueXP 工作负载工厂通知服务支持

BlueXP 工作负载工厂通知服务支持工作负载工厂向 BlueXP 警报服务或 Amazon SNS 主题发送通知。发送到 BlueXP 警报的通知会显示在 BlueXP 警报面板中。当工作负载工厂向 Amazon SNS 主题发布通知时，该主题的订阅者（例如人员或其他应用程序）会在为该主题配置的终端节点上收到通知（例如电子邮件或短信）。

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作负载工厂通知"]



== 2025年6月16日



=== 构建者的工作量



==== 克隆支持

您现在可以在 BlueXP 工作负载工厂中为 Builders 克隆项目。克隆项目时，Builders 会根据快照创建一个新项目，其配置与原始项目相同。克隆功能对于快速创建类似项目或进行测试非常有用。您可以按照 Builders 中的说明安装新的项目克隆。

https://docs.netapp.com/us-en/workload-builders/version-projects.html["管理 Builders 项目的 BlueXP 工作负载工厂版本"]



== 2025年6月8日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 全新精心设计的分析和问题修复支持

FSx for ONTAP 文件系统的自动容量管理现在作为配置分析包含在精心设计的状态仪表板中。

此外，工作负载工厂现在支持修复以下配置问题：

* SSD容量阈值
* 数据分层
* 计划的本地快照
* FSx for ONTAP 备份
* 远程数据复制
* 存储效率
* 自动容量管理


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["修复配置问题"]



== 2025年6月3日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 卷自动增长增强

现在，您可以设置卷的自动增长大小，以便卷大小可以超出业务需求和应用程序要求的预配置大小。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["启用卷自动增长"]



==== 架构完善的分析更新

工作负载工厂现在会分析您的 FSx for ONTAP 文件系统，以检查是否正在利用存储效率，包括数据压缩、压缩和重复数据删除。存储效率衡量文件系统利用可用空间的效率。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看存储效率的良好架构状态"]



==== 存储仪表板增强功能

从今天开始，当您从工作负载工厂控制台打开存储工作负载时，您将看到“仪表板”。全新设计的仪表板提供 FSx for ONTAP 系统的整体视图，包括文件系统数量、SSD 总容量、架构完善的状态概览、数据保护概览以及复制关系的运行状况。



==== 卷选项卡增强功能

存储工作负载对工作负载工厂控制台中 FSx for ONTAP 文件系统内的“卷”选项卡进行了增强。增强功能包括：

* *新卡*：SSD 容量、容量池和自主勒索软件防护 (ARP)
* *新列*：容量分布、已用 SSD 容量、已用容量池和 SSD 效率




==== 卷创建的存储效率更新

创建新卷时，默认启用存储效率，包括数据压缩、压缩和重复数据删除。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["在工作负载工厂中创建新卷"]



=== 数据库工作负载



==== PostgreSQL 和 Oracle 检测

现在，您可以在工作负载工厂控制台中发现 AWS 账户中运行 PostgreSQL 服务器数据库和 Oracle 数据库部署的实例。已发现的实例将显示在数据库清单中。



==== 更新了“优化”术语

工作负载工厂以前称为“优化”，现在使用“良好架构的问题”和“良好架构的状态”来描述数据库配置的分析，并使用“修复”来描述改善数据库配置以满足最佳实践建议的机会的补救措施。

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["工作负载工厂中的数据库环境配置分析"]



==== 改进实例的入门

工作负载工厂现在使用“注册”来表示实例管理，而不是使用“未检测到”、“未托管”或“托管”等术语。新的注册流程包括对实例进行身份验证和准备，以便您可以在工作负载工厂控制台中创建、监控、分析和修复数据库配置中的资源。注册流程中的准备步骤指示您的实例是否已准备好进行管理。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["实例管理"]



=== GenAI工作负载



==== 跟踪器可用于监控和跟踪操作

GenAI 现已提供 Tracker 监控功能。您可以使用 Tracker 监控和跟踪待处理、正在进行和已完成操作的进度和状态，查看操作任务和子任务的详细信息，诊断任何问题或故障，编辑失败操作的参数，以及重试失败的操作。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["使用 BlueXP 工作负载工厂中的 Tracker 监控工作负载操作"]



==== 为知识库选择重排序模型

现在，您可以通过选择与知识库配合使用的特定重排序模型来提高重排序查询结果的相关性。GenAI支持 Cohere Rerank 和 Amazon Rerank 模型。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



== 2025年5月4日



=== 数据库工作负载



==== 信息板增强功能

* 在BlueXP  工作负载出厂控制台中的选项卡之间导航时、可以使用跨帐户和跨区域视图。新视图可改进资源管理、监控和优化。
* 在信息板的*潜在节省*图块中、您将能够从Amazon El生 磁块存储切换到FSx for ONTAP或Amazon FSx for Windows File Server、从而快速查看可能节省的空间。




==== 可对数据库配置进行临时扫描

适用于数据库的BlueXP  工作负载工厂会自动扫描使用FSx for ONTAP存储的托管Microsoft SQL Server实例、以确定是否存在潜在的配置问题。现在、除了每日扫描之外、您还可以随时进行扫描。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 优化增强功能



===== 克隆清理

克隆清理评估和修复可识别和管理成本高昂的旧克隆。可以从BlueXP  工作负载出厂控制台中刷新或删除60天以上的克隆。



===== 延迟和取消配置分析

某些配置可能不适用于您的数据库环境。现在、您可以选择将特定配置分析推迟30天或取消分析。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了以下改进：

*将NetApp数据基础架构洞察作为数据源*：现在、工作负载工厂可直接与NetApp数据基础架构洞察连接、以便在使用EC2迁移顾问数据收集器时收集VMware部署信息。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== GenAI工作负载



==== 支持 NetApp Connector for Amazon Q Business

此版本的 GenAI 引入了对 NetApp Connector for Amazon Q Business 的支持，使您能够为 Amazon Q Business 创建连接器。快速轻松地利用Amazon Q Business AI助理、与构建Amazon Brock的GenAI知识库相比、初始配置更少。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["为 Amazon Q Business 创建 NetApp 连接器"]



==== 增强了聊天模式支持

现在、GenAI还支持在知识库中使用以下聊天模式：

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AI型号"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon T人 文本模型"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama模型"^]
* link:https://docs.ai21.com/["JAMBA 1.5型号"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohere命令模型"^]
* link:https://aws.amazon.com/bedrock/deepseek/["DeepSeek型号"^]


GenAI支持Amazon Brock支持的每个提供商的型号：link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Brock中支持的基础模型"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== 设置和管理



==== CloudShell自动完成支持

使用BlueXP  Workload Factory CloudShell时、您可以开始键入命令、然后按Tab键查看可用选项。如果存在多种可能、命令行界面将显示建议列表。此功能可最大限度地减少错误并加快命令执行速度、从而提高工作效率。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== 构建者的工作量



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



== 2025年3月30日



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了多项改进：

* *增强的卷分配指导*：EC2迁移顾问的"分类"和"打包"步骤中的卷分配信息增强了可读性和可用性。系统会显示有关每个卷的更多有用信息、使您能够更好地识别卷并确定如何分配卷。
* *提高了数据收集器脚本的效率*：在为小型VM部署收集数据时、EC2迁移顾问数据收集器脚本可优化CPU利用率。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



=== 设置和管理



==== CloudShell会报告ONTAP命令行界面命令的AI生成的错误响应

使用CloudShell时、每次发出ONTAP命令行界面命令并出现错误时、您都可以获得AI生成的错误响应、其中包括故障说明、故障原因和详细解决方案。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从工作负载出厂控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



== 2024年12月1日



=== 构建者的工作量



==== 构建者工作负载初始版本

适用于构建者的BlueXP  工作负载工厂可简化软件版本的使用和访问、无需自定义工具或脚本。它使您能够将软件版本作为即时克隆使用、并与Perforce Helix Core集成、作为开发流程的便利工作空间、从而节省时间和资源。

初始版本包括管理项目和工作空间以及使用CodeBox自动执行操作的功能。您还可以将"构建者"与Perforce Helix Core集成、以便管理每个项目的不同版本并在它们之间快速切换。
