---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 了解NetApp Workload Factory 中工作负载的最新变化。 
---
= NetApp Workload Factory 的最新变化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解NetApp Workload Factory 中工作负载的最新变化。



== 2026年1月4日



=== 数据库工作负载



==== 问我关于人工智能助手首页集成的问题

Workload Factory 控制台主页嵌入了 Ask me AI 助手，使您可以询问有关您自己的存储环境的问题，直接从您的环境中获取个性化见解，并参考以前的对话。您可以与“问我”进行交互，以了解您的工作负载、解决问题并了解更多关于工作负载工厂的信息——所有这些都无需离开控制台。



=== VMware工作负载



==== 问我关于人工智能助手首页集成的问题

Workload Factory 控制台主页嵌入了 Ask me AI 助手，使您可以询问有关您自己的存储环境的问题，直接从您的环境中获取个性化见解，并参考以前的对话。您可以与“问我”进行交互，以了解您的工作负载、解决问题并了解更多关于工作负载工厂的信息——所有这些都无需离开控制台。



== 2025年12月18日



=== 数据库工作负载



==== Active Directory 集成增强功能

使用“高级创建”选项部署 Microsoft SQL Server 时，数据库工作负载工厂将包含三个新的 Active Directory (AD) 字段。这些增强功能允许您指定 Active Directory 加入首选项并使用托管服务帐户。

新增的 AD 字段包括：

* 首选域控制器
* 首选组织单元路径
* 目标 Active Directory 组


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["部署 Microsoft SQL Server"]



== 2025年12月4日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 支持用于ONTAP的 FSx 的 AWS S3 访问点

NetApp Workload Factory为您的 FSx for ONTAP文件系统提供 AWS S3 访问点。您可以使用 S3 访问点创建卷，将 S3 访问点分配给现有卷，并从 Workload Factory 控制台管理 S3 访问点。使用 S3 访问点，您可以通过 AWS S3 API 访问驻留在 SMB/CIFS 或 NFS 卷上的文件数据。这样，您就可以将现有数据与来自支持 S3 访问点的 AWS 服务的 GenAI、ML 和分析功能集成在一起。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["使用 S3 接入点创建卷"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["管理卷的 S3 访问点"]




== 2025年11月27日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== NetApp Workload Factory中的块设备支持

NetApp Workload Factory中新引入的块设备支持，可更有效地管理您的块设备。此功能可让您查看 iSCSI LUN 的详细信息并增加其容量，从而为您的存储需求提供更大的灵活性。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["在工作负载工厂中管理块设备"]



==== 精心设计的分析更新

Workload Factory 会分析您的 FSx for ONTAP文件系统，以识别以下配置：

* 删除不必要的快照：检查卷中是否存在过时且不必要的快照，以便将其删除以降低成本。
* FlexGroup容量重新平衡：检查FlexGroup容量是否在其成员容量之间保持均衡，以确保最佳性能。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看 FSx for ONTAP文件系统的良好架构状态"]



==== NetApp Workload Factory中的 EMS 事件 AI 分析器

NetApp Workload Factory推出了一款基于 AI 的ONTAP事件管理系统 (EMS) 事件分析器。此功能通过分析 EMS 事件数据，提供见解和建议，帮助您快速识别和解决问题。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["在工作负载工厂中分析 EMS 事件"]



==== 监控 FSx for ONTAP文件系统的成本和使用趋势

您可以直接从NetApp Workload Factory控制台监控 FSx for ONTAP文件系统的成本和使用趋势。此功能提供存储消耗和成本指标以及详细成本，帮助您优化资源分配和预算规划。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["在 Workload Factory 中跟踪 FSx for ONTAP文件系统的成本"]



==== 在NetApp Workload Factory中管理文件系统的 FSx 标签

直接从NetApp Workload Factory控制台轻松管理文件系统的 FSx 标签。此功能允许您添加、编辑或删除标签，从而更好地组织和分类您的 FSx for ONTAP文件系统。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["在工作负载工厂中管理 FSx 标签"]



==== 调整 FSx for ONTAP文件系统的缓存容量

您可以通过工作负载工厂控制台增加和减少缓存卷的容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["在工作负载工厂中管理缓存卷"]



=== 数据库工作负载



==== 优化 Amazon Elastic Block Store (EBS) 数据库节省计算器

两个新的计算器功能改进了使用 EBS 存储运行多个实例时的成本节约分析，以便您可以通过切换到 FSx for ONTAP来节省更多成本。

* Workload Factory 为多个数据库主机在单个 FSx for ONTAP文件系统上提供统一的存储解决方案。这种整合通过减少多个数据库主机所需的文件系统数量来优化存储成本，从而提高成本效益。
* Workload Factory 分析您的 EBS 性能使用情况，然后建议最佳且最具成本效益的 FSx for ONTAP配置。


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["探索已检测到的 EBS 主机的节省方案。"]



==== 针对架构完善的仪表板，提供 Excel 报告。

您可以下载一份结构完善的仪表板的 Excel 报告。该报告提供了数据库资源的良好架构状态，并针对所有资源配置（包括操作系统和ONTAP 的子配置）提出了建议。



==== 适用于 Oracle 数据库的错误日志分析器

Agentic AI 驱动的错误日志分析器适用于 Oracle 数据库。该功能利用先进的机器学习算法自动检测和分析日志文件中的错误。该工具旨在通过根据日志中识别的模式向开发人员提供可操作的见解和建议来简化故障排除过程。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["了解有关 Agentic AI 驱动的错误日志分析器的更多信息"]



==== 针对 Oracle 的良好架构分析

精心设计的分析包括两种新的存储容量配置。该分析评估并修复了现有 Oracle 数据库部署中与交换空间分配和文件系统余量相关的配置问题。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在 Workload Factory 中实施架构良好的数据库配置"]



=== VMware工作负载



==== 计算迁移到 Amazon Elastic VMware Service 为特定区域节省的成本

现在，您可以探索不同云迁移部署选项的价值，优化解决方案评估方面的投入，并深入了解有可能在云端带来价值和节省的解决方案。

您还可以查看使用 FSx for ONTAP进行 EVS 部署可以节省的 vCPU 核心数。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["使用NetApp Workload Factory探索 Amazon Elastic VMware Service 的节省方案"]



=== 设置和管理



==== 存储权限更新

FSx for ONTAP EMS 事件分析器使用 _operations and remediation_ 权限策略中的以下 Amazon Bedrock 权限来获取存储工作负载的事件数据。

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限参考变更日志"]



== 2025年11月2日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 缓存卷管理

您可以在 Workload Factory 控制台中执行以下缓存卷管理操作：

* 编辑缓存名称
* 增加缓存卷的容量
* 编辑缓存卷的挂载路径或导出策略
* 更改缓存卷的缓存方法或模式
* 预先填充缓存卷
* 删除缓存卷


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["管理缓存卷"]



==== 可自动进行 inode 管理

您可以启用自动 inode 管理，而无需启用自动容量管理。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["启用自动 inode 管理"]



==== 容量和 inode 使用情况的阈值警告设置

容量和 inode 使用情况均有阈值警告。您可以在启用自动容量或 inode 管理时设置这些阈值。要使用此设置，您需要使用以下方式配置通知：link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory通知服务"^] 。



==== 容量减少可用

您可以在NetApp Workload Factory中减小 NFS 和 SMB/CIFS 卷的大小。此功能允许您减小不再需要的卷的大小，从而更好地管理存储资源。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["减少体积"]



==== 增强型 FSx for ONTAP资源状态

Workload Factory 增强了“配置错误”资源状态，使其包含对资源实际问题的解释。



==== 精心设计的分析更新

Workload Factory 会分析您的 FSx for ONTAP文件系统，以识别以下配置：

* 卷利用率接近满：检查是否有任何卷已使用 80% 或以上的文件容量。这有助于您确定可能需要额外产能的销量。
* 未经授权访问卷：检查是否可以使用 NFS 或 SMB/CIFS 挂载路径访问 iSCSI 卷，并允许您删除对卷的未经授权访问，以避免安全风险。




==== Workload Factory for Storage 的权限变更

Workload Factory 可以更清晰地说明执行特定操作所需的权限，并允许您精细地选择所需的权限。添加凭据时，您将有三个权限选项可供选择，而不是之前的权限模型（_只读_和_读/写_）。新的权限模型将权限策略分解如下：

* 查看、规划和分析：查看 FSx for ONTAP文件系统，了解系统运行状况，获取系统架构完善的分析，并探索节省成本的方法。
* _操作和修复_：执行操作任务，例如调整文件系统容量和修复文件系统配置问题。
* 文件系统创建和删除：创建和删除ONTAP文件系统和存储虚拟机的 FSx。


添加凭据时，您可以根据要授予 Workload Factory 的访问级别，选择一个或多个权限策略。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 权限参考"]



==== FSx 的ONTAP网络保险库支持

您可以使用 FSx for ONTAP作为网络保险库架构中的源或目标来创建网络保险库。网络保险库为存储关键数据提供安全隔离的环境，保护数据免受勒索软件和其他网络威胁的侵害。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["使用 FSx 为ONTAP设置网络保险库"]



=== 数据库工作负载



==== 仪表盘改进

新的仪表板经过简化和更好地组织，可以在一个屏幕上更清晰地概览数据库资源和工作负载工厂的关键功能；一张卡片突出显示数据库资源，一张卡片提供有关架构良好评分和分析的信息，一张卡片显示错误分析，两张卡片显示每月成本和潜在节省，一张卡片显示有关沙盒的信息。



==== 针对 Oracle 的良好架构分析

精心设计的分析包括对 Oracle 配置的以下评估和修复：

* 使用 NFS 协议的存储配置操作系统：评估并修复现有 Oracle 数据库部署的 NFS 配置问题。
* 使用 iSCSI 协议的存储配置操作系统：评估并修复现有 Oracle 数据库部署的 iSCSI 配置问题。
* 使用自动存储管理 (ASM) 的存储配置操作系统：评估现有 Oracle 数据库部署的 ASM 配置问题。


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在 Workload Factory 中实施架构良好的数据库配置"]



==== 数据库工作负载工厂的权限变更

Workload Factory for Databases 更新了权限策略，以便更清晰地说明特定操作所需的权限，并允许您更精细地选择所需的权限。添加凭据时，您将有三个权限选项可供选择，而不是之前的权限模型（_只读_和_读/写_）。新的权限模型将权限策略分解如下：

* 查看、规划和分析：查看数据库资源清单，了解资源运行状况，审查数据库配置的架构分析，获取错误日志分析，并探索节省成本的方案。
* 操作和修复：对数据库资源执行操作任务，并修复数据库配置和底层 FSx for ONTAP文件系统存储的问题。
* 数据库主机创建：根据最佳实践部署数据库主机和底层用于ONTAP文件系统存储的 FSx。


添加凭据时，您可以根据要授予 Workload Factory for Databases 的访问级别，选择一个或多个权限策略。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 权限参考"^]



==== 新增了设计精良的仪表盘界面。

数据库菜单中新增了一个名为“架构完善的仪表盘”的屏幕。通过此屏幕，您可以获得整个数据库环境配置状态的汇总视图。



==== NetApp Backup and Recovery中数据库部署的编辑保护

在 Workload Factory 控制台中，您可以选择编辑受保护资源的保护，然后您将被重定向到NetApp Console中的备份和恢复，在那里您可以修改保护策略或计划。

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["数据库部署的编辑保护"]



==== 错误分析功能支持按标签进行错误筛选

使用 Workload Factory 中的错误分析功能时，您可以按面向基础架构的标签筛选和查看 Microsoft SQL Server 错误日志。这项增强功能可帮助您快速对问题进行分类、排查和解决问题。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["使用标签筛选分析错误日志"^]



=== VMware工作负载



==== 在 FSx for ONTAP文件系统部署向导中引入 Amazon Elastic VMware Service 首选项

当您部署 FSx for ONTAP文件系统以用作 Amazon Elastic VMware Service 的外部 NFS 数据存储时，现在可以选择数据存储将连接到的 EVS 环境。此功能会自动填充部署向导中的多个字段，以简化部署过程。

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["部署推荐的适用于ONTAP文件系统的 FSx"]



==== VMware 工作负载的权限变更

VMware 工作负载能够更清晰地说明特定操作所需的权限，并允许您精细地选择所需的权限。添加凭据时，您将有两个权限选项可供选择，而不是之前的权限模型（_只读_和_读/写_）。新的权限模型将权限策略分解如下：

* 查看、规划和分析：查看 EVS 虚拟化环境的清单，获取系统架构完善的分析，并探索节省成本的方法。
* 数据存储部署和连接：将推荐的 VM 布局部署到 Amazon EVS、Amazon EC2 或 VMware Cloud on AWS vSphere 集群，并使用定制的Amazon FSx for NetApp ONTAP文件系统作为外部数据存储。


添加凭据时，您可以根据要向 VMware 工作负载提供的访问级别，选择一个或多个权限策略。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 权限参考"^]



==== Amazon EC2 迁移顾问改进

此版本的NetApp Workload Factory for VMware 对迁移顾问体验进行了多项改进：

* *保存或下载迁移计划*：您现在可以将迁移计划保存或下载为 PDF 或 CSV 文件。保存迁移计划时，该计划将保存到您的 Workload Factory 帐户中。




=== 设置和管理



==== 权限更新

在此版本中，我们对存储、数据库和 VMware 工作负载的权限策略进行了重大更新，以增强安全性和用户控制。您可以更精细地自定义权限设置，根据需要添加或取消权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 的权限参考"]



==== 存储的新通知

NetApp Workload Factory通知服务包含存储自动 inode 管理的通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory 通知"]



==== 自动容量和 inode 管理的阈值警告

可以为存储设置自动容量和 inode 管理，并设置警告阈值，该阈值会触发 Workload Factory 通知服务的通知。要使用此功能，必须先启用工作负载工厂通知服务。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置NetApp Workload Factory的通知"]
