---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 了解BlueXP  工作负载工厂中工作负载的最新变化。 
---
= BlueXP  工作负载出厂时的最新变更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解BlueXP  工作负载工厂中工作负载的最新变化。



== 2025年6月3日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 卷自动增长增强

现在，您可以设置卷的自动增长大小，以便卷大小可以超出业务需求和应用程序要求的预配置大小。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["启用卷自动增长"]



==== 架构完善的分析更新

工作负载工厂现在会分析您的 FSx for ONTAP 文件系统，以检查是否正在利用存储效率，包括数据压缩、压缩和重复数据删除。存储效率衡量文件系统利用可用空间的效率。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看存储效率的良好架构状态"]



==== 存储仪表板增强功能

从今天开始，当您从工作负载工厂控制台打开存储工作负载时，您将看到“仪表板”。全新设计的仪表板提供 FSx for ONTAP 系统的整体视图，包括文件系统数量、SSD 总容量、架构完善的状态概览、数据保护概览以及复制关系的运行状况。



==== 卷选项卡增强功能

存储工作负载对工作负载工厂控制台中 FSx for ONTAP 文件系统内的“卷”选项卡进行了增强。增强功能包括：

* *新卡*：SSD 容量、容量池和自主勒索软件防护 (ARP)
* *新列*：容量分布、已用 SSD 容量、已用容量池和 SSD 效率




==== 卷创建的存储效率更新

创建新卷时，默认启用存储效率，包括数据压缩、压缩和重复数据删除。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["在工作负载工厂中创建新卷"]



=== 数据库工作负载



==== PostgreSQL 和 Oracle 检测

现在，您可以在工作负载工厂控制台中发现 AWS 账户中运行 PostgreSQL 服务器数据库和 Oracle 数据库部署的实例。已发现的实例将显示在数据库清单中。



==== 更新了“优化”术语

工作负载工厂以前称为“优化”，现在使用“良好架构的问题”和“良好架构的状态”来描述数据库配置的分析，并使用“修复”来描述改善数据库配置以满足最佳实践建议的机会的补救措施。

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["工作负载工厂中的数据库环境配置分析"]



==== 改进了主机实例的入职培训

工作负载工厂现在使用“注册”来表示主机实例的注册，而不是像以前那样使用“未检测到”、“未托管”或“托管”等术语。新的注册流程包括对主机实例进行身份验证和准备，以便您可以在工作负载工厂控制台中创建、监控、分析和修复数据库配置中的资源。注册流程中的准备步骤指示您的主机实例是否已准备好进行管理。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["实例管理"]



=== GenAI工作负载



==== 跟踪器可用于监控和跟踪操作

GenAI 现已提供 Tracker 监控功能。您可以使用 Tracker 监控和跟踪待处理、正在进行和已完成操作的进度和状态，查看操作任务和子任务的详细信息，诊断任何问题或故障，编辑失败操作的参数，以及重试失败的操作。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["使用 BlueXP 工作负载工厂中的 Tracker 监控工作负载操作"]



==== 为知识库选择重排序模型

现在，您可以通过选择与知识库配合使用的特定重排序模型来提高重排序查询结果的相关性。GenAI支持 Cohere Rerank 和 Amazon Rerank 模型。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



== 2025年5月4日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 针对ONTAP文件系统FSx的自动防软件保护

利用自动勒索软件保护(ARP)保护数据、此功能可在NAS (NFS/SMB)环境中使用工作负载分析来检测可能是勒索软件攻击的异常活动并发出警告。当怀疑发生攻击时、ARP还会创建新的、不可变更的快照、您可以从中还原数据。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["利用自动防兰森保护功能保护您的数据"]



==== FlexGroup卷重新平衡增强功能

BlueXP  工作负载出厂时引入了FlexGroup卷重新平衡向导、其中包含多个用于重新平衡FlexGroup卷中数据的布局选项。重新平衡会将数据均匀地重新分布到FlexGroup成员卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["重新平衡FlexGroup卷中的容量"]



==== 为FSx for ONTAP文件系统实施最佳实践

BlueXP  工作负载工厂提供了一个信息板、您可以在其中查看文件系统配置的架构良好状态。您可以利用此分析为FSx for ONTAP文件系统实施最佳实践。文件系统配置分析包括以下配置：SSD容量阈值、计划的本地快照、计划的ONTAP备份FSx、数据分层和远程数据复制。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["了解对文件系统配置进行精心设计的分析"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["为文件系统实施最佳实践"]




==== 双协议卷安全模式选项

您可以选择NTFS或UNIX作为卷的安全模式、以确定用户和权限访问卷的方法。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["创建卷"]



==== 复制增强功能



===== 支持从FSx for ONTAP反向复制到内部

现在、可以从FSx for ONTAP文件系统从工作负载出厂控制台向内部ONTAP集群进行反向复制。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["反向复制"]



===== 数据保护卷复制

现在、您可以复制数据保护卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["复制数据保护卷"]



===== 选择多个卷

您可以选择多个卷、以便准确选择要复制的卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["创建复制关系"]



===== 长期保留策略标签

如果为复制关系启用长期保留、则源卷和目标卷标签必须完全匹配。现在、BlueXP  工作负载工厂可以自动为您创建缺少的源卷标签。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["创建复制关系"]



==== FSx for ONTAP文件名可在创建卷时显示

我们提高了FSx for ONTAP文件系统在卷创建期间的可见性。创建卷时、您将看到FSx for ONTAP文件系统、因此您可以确切地知道卷的创建位置。



==== 可在存储工作负载中查看AWS帐户

我们提高了客户对整个存储工作负载的可见性。导航到*卷*、*存储VM*和*复制*选项卡时、您将看到AWS帐户。



==== 链接关联增强功能

* 您可以在清单选项卡中快速关联FSx for ONTAP文件系统中的链接。
* BlueXP  工作负载工厂现在支持使用备用ONTAP用户凭据进行链接关联。




==== 支持对AWS专有信息管理器进行链接身份验证

现在、您可以选择使用AWS机密管理器中的密钥对链接进行身份验证、这样就不必使用BlueXP  工作负载工厂中存储的凭据。



==== 跟踪器响应支持

Tracker现在提供API响应、以便您可以查看与任务相关的REST API输出。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["使用Tracker监控操作"]



==== 从备份还原卷时进行容量验证

从备份还原卷时、BlueXP  工作负载出厂时会确定您是否有足够的容量进行还原、如果没有、则可以自动添加SSD存储层容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["从备份还原卷"]



==== 支持备用ONTAP用户凭据

工作负载工厂现在支持使用备用ONTAP凭据集来创建文件系统、从而最大限度地降低安全风险。您可以选择一组不同的ONTAP凭据、也可以选择不为fsxadmin和vsaadmin用户提供密码、而不是仅使用fsxadmin用户。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== 数据库工作负载



==== 信息板增强功能

* 在BlueXP  工作负载出厂控制台中的选项卡之间导航时、可以使用跨帐户和跨区域视图。新视图可改进资源管理、监控和优化。
* 在信息板的*潜在节省*图块中、您将能够从Amazon El生 磁块存储切换到FSx for ONTAP或Amazon FSx for Windows File Server、从而快速查看可能节省的空间。




==== 可对数据库配置进行临时扫描

适用于数据库的BlueXP  工作负载工厂会自动扫描使用FSx for ONTAP存储的托管Microsoft SQL Server实例、以确定是否存在潜在的配置问题。现在、除了每日扫描之外、您还可以随时进行扫描。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 优化增强功能



===== 克隆清理

克隆清理评估和修复可识别和管理成本高昂的旧克隆。可以从BlueXP  工作负载出厂控制台中刷新或删除60天以上的克隆。



===== 延迟和取消配置分析

某些配置可能不适用于您的数据库环境。现在、您可以选择将特定配置分析推迟30天或取消分析。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了以下改进：

*将NetApp数据基础架构洞察作为数据源*：现在、工作负载工厂可直接与NetApp数据基础架构洞察连接、以便在使用EC2迁移顾问数据收集器时收集VMware部署信息。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== GenAI工作负载



==== 支持 NetApp Connector for Amazon Q Business

此版本的 GenAI 引入了对 NetApp Connector for Amazon Q Business 的支持，使您能够为 Amazon Q Business 创建连接器。快速轻松地利用Amazon Q Business AI助理、与构建Amazon Brock的GenAI知识库相比、初始配置更少。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["为 Amazon Q Business 创建 NetApp 连接器"]



==== 增强了聊天模式支持

现在、GenAI还支持在知识库中使用以下聊天模式：

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AI型号"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon T人 文本模型"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama模型"^]
* link:https://docs.ai21.com/["JAMBA 1.5型号"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohere命令模型"^]
* link:https://aws.amazon.com/bedrock/deepseek/["DeepSeek型号"^]


GenAI支持Amazon Brock支持的每个提供商的型号：link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Brock中支持的基础模型"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== 设置和管理



==== CloudShell自动完成支持

使用BlueXP  Workload Factory CloudShell时、您可以开始键入命令、然后按Tab键查看可用选项。如果存在多种可能、命令行界面将显示建议列表。此功能可最大限度地减少错误并加快命令执行速度、从而提高工作效率。



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



== 2025年4月4日



=== 数据库工作负载



==== 优化增强功能

在优化数据库环境时、可以使用新的优化评估、更新和显示多个资源。



===== 故障恢复能力评估

这些增强功能包括新的故障恢复能力评估、用于检查是否为数据库环境配置了数据冗余和灾难恢复功能。

* FSx for ONTAP备份：分析为SQL Server实例的卷提供服务的ONTAP文件系统FSx是否为ONTAP备份配置了计划FSx。
* 跨区域复制：评估为Microsoft SQL Server实例提供服务的ONTAP文件系统FSx是否配置了跨区域复制。




===== 计算修复

接收端扩展(RSS)修复功能可配置RSS、以便在多个处理器之间分布网络处理、并确保高效分布负载。



===== 本地快照修复

本地快照修复可为Microsoft SQL Server实例的卷设置快照策略、以便在数据丢失时保持数据库环境的弹性。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



===== 支持多资源选择

在优化数据库配置时、您现在可以选择特定资源、而不是所有资源。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



==== 改进了清单视图

工作负载出厂控制台中的"清单"选项卡已经过简化、因此它仅包含在Amazon FSx for NetApp ONTAP上运行的SQL Server。现在、您可以在"浏览节省量"选项卡中找到在内部部署且在Amazon Elabic Block Store和Amazon FSx for Windows File Server上运行的SQL Server。



==== 快速创建可用于PostgreSQL服务器部署

您可以使用此快速部署选项创建具有HA配置和嵌入式最佳实践的PostgreSQL服务器。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["在BlueXP  工作负载工厂中创建PostgreSQL服务器"]



== 2025年3月30日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 横向扩展系统的自动容量管理

现在、工作负载出厂时会扫描卷中的可用Inode、并根据配置的自动容量管理阈值增加其计数。此功能支持横向扩展系统的自动容量管理。您可以在自动容量管理过程中启用inode管理。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["启用自动容量管理"]



==== FlexGroup重新平衡API

BlueXP  工作负载出厂时会发布FlexGroup重新平衡API、您可以通过此API执行计划来重新平衡FlexGroup中的数据。重新平衡会将数据均匀地重新分布到成员卷。

link:https://console.workloads.netapp.com/api-doc["BlueXP  工作负载出厂API文档"]



==== 复制数据表单包括使用情形

复制数据表现在包括一些用例、便于您填写表单。您可以选择以下数据复制用例之一：迁移、热灾难恢复、冷灾难恢复、归档或其他。选择使用情形后、工作负载出厂时会根据最佳实践建议相应的值。您可以接受预选值或自定义表单中的值。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["复制数据"]



==== 数据层策略术语变更

现在、当您在创建卷、复制数据或更新现有分层策略期间选择分层策略时、您会发现用于描述分层策略的新术语。

* _平衡(自动)_
* 成本优化(全部)_
* _性能优化(仅限Snapshot)_




==== 用于创建文件系统的安全组详细信息

在FSx for ONTAP文件系统创建过程中会创建一个安全组。现在、您可以查看安全组详细信息、包括协议、端口和角色。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["创建文件系统"]



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了多项改进：

* *增强的卷分配指导*：EC2迁移顾问的"分类"和"打包"步骤中的卷分配信息增强了可读性和可用性。系统会显示有关每个卷的更多有用信息、使您能够更好地识别卷并确定如何分配卷。
* *提高了数据收集器脚本的效率*：在为小型VM部署收集数据时、EC2迁移顾问数据收集器脚本可优化CPU利用率。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



=== GenAI工作负载



==== 增强了文件类型支持

此版本的GenAI引入了在从数据源中精妙设计文件时对JSON和JSONP文件格式的支持 `.json`。支持包含嵌套对象的JSON文件、但对嵌套阵列的支持有限。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["支持的数据源文件格式"]



==== 为外部聊天机器人示例应用程序提供国际化支持

现在、您可以轻松地将GenAI示例外部聊天机器人应用程序的用户界面更改为其他语言或区域设置。

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["GenAI外部示例聊天机器人应用程序"]



==== 支持Anthropic Claude Sonnet 3.7聊天模式

GenAI现在支持Anthropic Claude 3.7 Sonnet聊天模式。CLODE 3.7 Sonnet的测试版功能允许每个请求最多128K输出令牌、并支持新的计算机使用操作。将来的GenAI版本将支持CLAUDE 3.7 Sonnet扩展思维模式。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



==== 支持从通用NFS/SMB共享添加数据源

现在、您可以使用工作负载出厂API从通用NFSv3、NFSv4或SMB共享添加数据源。从NFS或SMB共享添加数据源时、知识库卷仍保留在Amazon FSx for NetApp ONTAP卷上。工作负载出厂Web UI将在未来版本中支持此功能。

link:https://console.workloads.netapp.com/api-doc["使用工作负载出厂API"^]



==== VPC对等支持

现在、您可以在同一区域部署GenAI基础架构link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["对等虚拟私有云(VPC)"^]、并使用相同的AWS帐户。您可以在VPC中部署AI引擎、然后在对等VPC中创建知识库、并选择位于对等VPC中的Amazon FSx for NetApp ONTAP文件系统。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



=== 设置和管理



==== CloudShell会报告ONTAP命令行界面命令的AI生成的错误响应

使用CloudShell时、每次发出ONTAP命令行界面命令并出现错误时、您都可以获得AI生成的错误响应、其中包括故障说明、故障原因和详细解决方案。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从工作负载出厂控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



== 2025年3月2日



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了多项改进：

* *估计实例类型*：迁移顾问现在可以检查您的环境要求、并为每个VM提供估计的Amazon EC2实例类型。您可以选择在迁移顾问的范围步骤中包括每个VM的估计实例类型。
* *推荐Amazon EBS卷的能力*：由于特定地区的特定容量或性能需求、迁移顾问现在可以建议将数据卷迁移到Amazon Elelic Block Store (EBS)、而不是Amazon FSx for NetApp ONTAP。
* *增强型文件系统自动分配*：Amazon FSx for NetApp ONTAP文件系统分配已得到改进、可以更好地优化成本并最大限度地降低吞吐量。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2025年2月2日



=== 设置和管理



==== BlueXP  工作负载出厂控制台中提供了CloudShell

您可以从BlueXP  工作负载出厂控制台中的任何位置访问CloudShell。通过CloudShell、您可以使用在BlueXP  帐户中提供的AWS和ONTAP凭据、并在类似于Shell的环境中执行AWS命令行界面命令或ONTAP命令行界面命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== 更新数据库的权限

现在，以下权限在_read_模式下可用于数据库： `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]
