---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 了解BlueXP  工作负载工厂中工作负载的最新变化。 
---
= BlueXP  工作负载出厂时的最新变更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解BlueXP  工作负载工厂中工作负载的最新变化。



== 2025年5月4日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 针对ONTAP文件系统FSx的自动防软件保护

利用自动勒索软件保护(ARP)保护数据、此功能可在NAS (NFS/SMB)环境中使用工作负载分析来检测可能是勒索软件攻击的异常活动并发出警告。当怀疑发生攻击时、ARP还会创建新的、不可变更的快照、您可以从中还原数据。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["利用自动防兰森保护功能保护您的数据"]



==== FlexGroup卷重新平衡增强功能

BlueXP  工作负载出厂时引入了FlexGroup卷重新平衡向导、其中包含多个用于重新平衡FlexGroup卷中数据的布局选项。重新平衡会将数据均匀地重新分布到FlexGroup成员卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["重新平衡FlexGroup卷中的容量"]



==== 为FSx for ONTAP文件系统实施最佳实践

BlueXP  工作负载工厂提供了一个信息板、您可以在其中查看文件系统配置的架构良好状态。您可以利用此分析为FSx for ONTAP文件系统实施最佳实践。文件系统配置分析包括以下配置：SSD容量阈值、计划的本地快照、计划的ONTAP备份FSx、数据分层和远程数据复制。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["了解对文件系统配置进行精心设计的分析"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["为文件系统实施最佳实践"]




==== 双协议卷安全模式选项

您可以选择NTFS或UNIX作为卷的安全模式、以确定用户和权限访问卷的方法。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["创建卷"]



==== 复制增强功能



===== 支持从FSx for ONTAP反向复制到内部

现在、可以从FSx for ONTAP文件系统从工作负载出厂控制台向内部ONTAP集群进行反向复制。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["反向复制"]



===== 数据保护卷复制

现在、您可以复制数据保护卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["复制数据保护卷"]



===== 选择多个卷

您可以选择多个卷、以便准确选择要复制的卷。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["创建复制关系"]



===== 长期保留策略标签

如果为复制关系启用长期保留、则源卷和目标卷标签必须完全匹配。现在、BlueXP  工作负载工厂可以自动为您创建缺少的源卷标签。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["创建复制关系"]



==== FSx for ONTAP文件名可在创建卷时显示

我们提高了FSx for ONTAP文件系统在卷创建期间的可见性。创建卷时、您将看到FSx for ONTAP文件系统、因此您可以确切地知道卷的创建位置。



==== 可在存储工作负载中查看AWS帐户

我们提高了客户对整个存储工作负载的可见性。导航到*卷*、*存储VM*和*复制*选项卡时、您将看到AWS帐户。



==== 链接关联增强功能

* 您可以在清单选项卡中快速关联FSx for ONTAP文件系统中的链接。
* BlueXP  工作负载工厂现在支持使用备用ONTAP用户凭据进行链接关联。




==== 支持对AWS专有信息管理器进行链接身份验证

现在、您可以选择使用AWS机密管理器中的密钥对链接进行身份验证、这样就不必使用BlueXP  工作负载工厂中存储的凭据。



==== 跟踪器响应支持

Tracker现在提供API响应、以便您可以查看与任务相关的REST API输出。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["使用Tracker监控操作"]



==== 从备份还原卷时进行容量验证

从备份还原卷时、BlueXP  工作负载出厂时会确定您是否有足够的容量进行还原、如果没有、则可以自动添加SSD存储层容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["从备份还原卷"]



==== 支持备用ONTAP用户凭据

工作负载工厂现在支持使用备用ONTAP凭据集来创建文件系统、从而最大限度地降低安全风险。您可以选择一组不同的ONTAP凭据、也可以选择不为fsxadmin和vsaadmin用户提供密码、而不是仅使用fsxadmin用户。



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



=== 数据库工作负载



==== 信息板增强功能

* 在BlueXP  工作负载出厂控制台中的选项卡之间导航时、可以使用跨帐户和跨区域视图。新视图可改进资源管理、监控和优化。
* 在信息板的*潜在节省*图块中、您将能够从Amazon El生 磁块存储切换到FSx for ONTAP或Amazon FSx for Windows File Server、从而快速查看可能节省的空间。




==== 可对数据库配置进行临时扫描

适用于数据库的BlueXP  工作负载工厂会自动扫描使用FSx for ONTAP存储的托管Microsoft SQL Server实例、以确定是否存在潜在的配置问题。现在、除了每日扫描之外、您还可以随时进行扫描。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 优化增强功能



===== 克隆清理

克隆清理评估和修复可识别和管理成本高昂的旧克隆。可以从BlueXP  工作负载出厂控制台中刷新或删除60天以上的克隆。



===== 延迟和取消配置分析

某些配置可能不适用于您的数据库环境。现在、您可以选择将特定配置分析推迟30天或取消分析。



==== 删除内部评估记录

在探讨了Microsoft SQL Server内部主机的节省之后、您可以选择从BlueXP  工作负载出厂时删除内部主机记录。



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了以下改进：

*将NetApp数据基础架构洞察作为数据源*：现在、工作负载工厂可直接与NetApp数据基础架构洞察连接、以便在使用EC2迁移顾问数据收集器时收集VMware部署信息。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



=== GenAI工作负载



==== 支持NetApp ONTAP Connector for Amazon Q

此版本的GenAI支持适用于Amazon Q的NetApp ONTAP连接器、使您能够为Amazon Q Business创建连接器。快速轻松地利用Amazon Q Business AI助理、与构建Amazon Brock的GenAI知识库相比、初始配置更少。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["为Amazon Q Business创建一个GenAI连接器"]



==== 增强了聊天模式支持

现在、GenAI还支持在知识库中使用以下聊天模式：

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AI型号"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon T人 文本模型"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llama模型"^]
* link:https://docs.ai21.com/["JAMBA 1.5型号"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohere命令模型"^]
* link:https://aws.amazon.com/bedrock/deepseek/["DeepSeek型号"^]


GenAI支持Amazon Brock支持的每个提供商的型号：link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Brock中支持的基础模型"^]

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["创建GenAI知识库"]



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



=== 设置和管理



==== CloudShell自动完成支持

使用BlueXP  Workload Factory CloudShell时、您可以开始键入命令、然后按Tab键查看可用选项。如果存在多种可能、命令行界面将显示建议列表。此功能可最大限度地减少错误并加快命令执行速度、从而提高工作效率。



==== 更新了权限术语

现在、工作负载出厂用户界面和文档使用"只读"来表示读取权限、使用"读写"来表示自动执行权限。



== 2025年4月4日



=== 数据库工作负载



==== 优化增强功能

在优化数据库环境时、可以使用新的优化评估、更新和显示多个资源。



===== 故障恢复能力评估

这些增强功能包括新的故障恢复能力评估、用于检查是否为数据库环境配置了数据冗余和灾难恢复功能。

* FSx for ONTAP备份：分析为SQL Server实例的卷提供服务的ONTAP文件系统FSx是否为ONTAP备份配置了计划FSx。
* 跨区域复制：评估为Microsoft SQL Server实例提供服务的ONTAP文件系统FSx是否配置了跨区域复制。




===== 计算修复

接收端扩展(RSS)修复功能可配置RSS、以便在多个处理器之间分布网络处理、并确保高效分布负载。



===== 本地快照修复

本地快照修复可为Microsoft SQL Server实例的卷设置快照策略、以便在数据丢失时保持数据库环境的弹性。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



===== 支持多资源选择

在优化数据库配置时、您现在可以选择特定资源、而不是所有资源。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



==== 改进了清单视图

工作负载出厂控制台中的"清单"选项卡已经过简化、因此它仅包含在Amazon FSx for NetApp ONTAP上运行的SQL Server。现在、您可以在"浏览节省量"选项卡中找到在内部部署且在Amazon Elabic Block Store和Amazon FSx for Windows File Server上运行的SQL Server。



==== 快速创建可用于PostgreSQL服务器部署

您可以使用此快速部署选项创建具有HA配置和嵌入式最佳实践的PostgreSQL服务器。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["在BlueXP  工作负载工厂中创建PostgreSQL服务器"]



== 2025年3月30日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 横向扩展系统的自动容量管理

现在、工作负载出厂时会扫描卷中的可用Inode、并根据配置的自动容量管理阈值增加其计数。此功能支持横向扩展系统的自动容量管理。您可以在自动容量管理过程中启用inode管理。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["启用自动容量管理"]



==== FlexGroup重新平衡API

BlueXP  工作负载出厂时会发布FlexGroup重新平衡API、您可以通过此API执行计划来重新平衡FlexGroup中的数据。重新平衡会将数据均匀地重新分布到成员卷。

link:https://console.workloads.netapp.com/api-doc["BlueXP  工作负载出厂API文档"]



==== 复制数据表单包括使用情形

复制数据表现在包括一些用例、便于您填写表单。您可以选择以下数据复制用例之一：迁移、热灾难恢复、冷灾难恢复、归档或其他。选择使用情形后、工作负载出厂时会根据最佳实践建议相应的值。您可以接受预选值或自定义表单中的值。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["复制数据"]



==== 数据层策略术语变更

现在、当您在创建卷、复制数据或更新现有分层策略期间选择分层策略时、您会发现用于描述分层策略的新术语。

* _平衡(自动)_
* 成本优化(全部)_
* _性能优化(仅限Snapshot)_




==== 用于创建文件系统的安全组详细信息

在FSx for ONTAP文件系统创建过程中会创建一个安全组。现在、您可以查看安全组详细信息、包括协议、端口和角色。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["创建文件系统"]



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了多项改进：

* *增强的卷分配指导*：EC2迁移顾问的"分类"和"打包"步骤中的卷分配信息增强了可读性和可用性。系统会显示有关每个卷的更多有用信息、使您能够更好地识别卷并确定如何分配卷。
* *提高了数据收集器脚本的效率*：在为小型VM部署收集数据时、EC2迁移顾问数据收集器脚本可优化CPU利用率。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



=== GenAI工作负载



==== 增强了文件类型支持

此版本的GenAI引入了在从数据源中精妙设计文件时对JSON和JSONP文件格式的支持 `.json`。支持包含嵌套对象的JSON文件、但对嵌套阵列的支持有限。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["支持的数据源文件格式"]



==== 为外部聊天机器人示例应用程序提供国际化支持

现在、您可以轻松地将GenAI示例外部聊天机器人应用程序的用户界面更改为其他语言或区域设置。

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["GenAI外部示例聊天机器人应用程序"]



==== 支持Anthropic Claude Sonnet 3.7聊天模式

GenAI现在支持Anthropic Claude 3.7 Sonnet聊天模式。CLODE 3.7 Sonnet的测试版功能允许每个请求最多128K输出令牌、并支持新的计算机使用操作。将来的GenAI版本将支持CLAUDE 3.7 Sonnet扩展思维模式。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



==== 支持从通用NFS/SMB共享添加数据源

现在、您可以使用工作负载出厂API从通用NFSv3、NFSv4或SMB共享添加数据源。从NFS或SMB共享添加数据源时、知识库卷仍保留在Amazon FSx for NetApp ONTAP卷上。工作负载出厂Web UI将在未来版本中支持此功能。

link:https://console.workloads.netapp.com/api-doc["使用工作负载出厂API"^]



==== VPC对等支持

现在、您可以在同一区域部署GenAI基础架构link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["对等虚拟私有云(VPC)"^]、并使用相同的AWS帐户。您可以在VPC中部署AI引擎、然后在对等VPC中创建知识库、并选择位于对等VPC中的Amazon FSx for NetApp ONTAP文件系统。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["创建GenAI知识库"]



=== 设置和管理



==== CloudShell会报告ONTAP命令行界面命令的AI生成的错误响应

使用CloudShell时、每次发出ONTAP命令行界面命令并出现错误时、您都可以获得AI生成的错误响应、其中包括故障说明、故障原因和详细解决方案。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从工作负载出厂控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



== 2025年3月3日



=== 数据库工作负载



==== PostgreSQL高可用性配置

现在、您可以为PostgreSQL服务器部署高可用性(HA)配置。

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["创建PostgreSQL服务器"]



==== 为PostgreSQL服务器创建提供Terraform支持

现在、您可以使用CodeBox中的Terraform部署PostgreSQL。

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["创建PostgreSQL数据库服务器"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["使用CodeBox中的Terraform"]




==== 本地快照计划的故障恢复能力评估

为数据库工作负载提供了新的故障恢复能力评估。我们将评估Microsoft SQL Server实例中的卷是否具有有效的计划快照策略。快照是数据的时间点副本、可帮助您的数据库环境在数据丢失时保持弹性。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



==== 数据库工作负载的MAXDOP修复

现在、适用于数据库的BlueXP  工作负载工厂支持针对最大并行度(MAXDOP)服务器配置进行修复。如果MAXDOP配置不是最佳配置、则可以让BlueXP  工作负载在出厂时为您优化配置。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



==== 通过电子邮件发送节省量分析报告

与FSx for ONTAP相比、在探索Amazon El生 性块存储和FSx for Windows文件服务器存储环境的节省空间时、您现在可以通过电子邮件将建议报告发送给您自己、团队成员和客户。



== 2025年3月2日



=== 适用于 NetApp ONTAP 的 Amazon FSX



==== 自动容量管理改进

启用自动容量管理后、BlueXP  Workload Factory现在会每30分钟检查一次文件系统是否达到其容量阈值、而不是每2小时检查一次。

达到容量阈值时、配置的IOPS设置不再受影响。



==== 不可变更的快照

现在、您可以锁定快照、使其在特定保留期限内不可改变。锁定可防止未经授权的访问和恶意删除快照。您可以在创建快照策略期间、创建手动快照时以及创建快照之后启用不可变快照。



==== 更新不可更改的文件

现在、您可以对不可变文件配置进行以下更改：保留策略、保留期限、自动提交期限和卷附加模式。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["管理不可配置文件"]



==== 数据复制增强功能

* 跨帐户复制：BlueXP  工作负载出厂控制台支持在两个AWS帐户之间进行复制以及复制管理。
* 暂停和恢复复制：您可以暂停(暂停)从源卷到目标卷的计划复制更新、然后在准备就绪后恢复复制计划。暂停期间、源卷和目标卷会彼此独立、目标卷会从只读过渡到读写。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["暂停和恢复复制关系"]





==== Tracker中的CloudShell事件

现在、您可以在Tracker中跟踪CloudShell事件。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["了解如何使用Tracker监控和跟踪操作"]



=== VMware工作负载



==== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对Amazon EC2迁移顾问体验进行了多项改进：

* *估计实例类型*：迁移顾问现在可以检查您的环境要求、并为每个VM提供估计的Amazon EC2实例类型。您可以选择在迁移顾问的范围步骤中包括每个VM的估计实例类型。
* *推荐Amazon EBS卷的能力*：由于特定地区的特定容量或性能需求、迁移顾问现在可以建议将数据卷迁移到Amazon Elelic Block Store (EBS)、而不是Amazon FSx for NetApp ONTAP。
* *增强型文件系统自动分配*：Amazon FSx for NetApp ONTAP文件系统分配已得到改进、可以更好地优化成本并最大限度地降低吞吐量。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



=== GenAI工作负载



==== 嵌入式聊天机器人增强功能

现在、您可以将问题和回答直接复制到剪贴板、调整聊天窗口的大小并更改其标题。此外、聊天响应现在可以包括表、这些表也是可复制的。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["测试GenAI知识库"]



==== 聊天响应引用支持

聊天回复现在包含引用、列出用于生成回复的文件和数据块。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["测试GenAI知识库"]



==== 增强了文件类型支持

此版本的GenAI提供了增强的文件支持：

* 聊天模式改进了CSV支持。这样、在从CSV文件查询数据时、可以做出更有用的响应。
* 现在、GenAI可以从数据源中安装Apache Parquet文件。
* GenAI现在支持载入包含图像的Microsoft Word DOCX文件。对DOCX文档中嵌入的图像进行扫描、对知识库查询的响应中包含嵌入图像中的文本洞察信息。


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["支持的数据源文件格式"]



== 2025年2月2日



=== 设置和管理



==== BlueXP  工作负载出厂控制台中提供了CloudShell

您可以从BlueXP  工作负载出厂控制台中的任何位置访问CloudShell。通过CloudShell、您可以使用在BlueXP  帐户中提供的AWS和ONTAP凭据、并在类似于Shell的环境中执行AWS命令行界面命令或ONTAP命令行界面命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== 更新数据库的权限

现在，以下权限在_read_模式下可用于数据库： `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]
