= 优化增强功能
:allow-uri-read: 




=== 优化增强功能

在优化数据库环境时、可以使用新的优化评估、更新和显示多个资源。



==== 故障恢复能力评估

这些增强功能包括新的故障恢复能力评估、用于检查是否为数据库环境配置了数据冗余和灾难恢复功能。

* FSx for ONTAP备份：分析为SQL Server实例的卷提供服务的ONTAP文件系统FSx是否为ONTAP备份配置了计划FSx。
* 跨区域复制：评估为Microsoft SQL Server实例提供服务的ONTAP文件系统FSx是否配置了跨区域复制。




==== 计算修复

接收端扩展(RSS)修复功能可配置RSS、以便在多个处理器之间分布网络处理、并确保高效分布负载。



==== 本地快照修复

本地快照修复可为Microsoft SQL Server实例的卷设置快照策略、以便在数据丢失时保持数据库环境的弹性。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



==== 支持多资源选择

在优化数据库配置时、您现在可以选择特定资源、而不是所有资源。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["优化配置"]



=== 改进了清单视图

工作负载出厂控制台中的"清单"选项卡已经过简化、因此它仅包含在Amazon FSx for NetApp ONTAP上运行的SQL Server。现在、您可以在"浏览节省量"选项卡中找到在内部部署且在Amazon Elabic Block Store和Amazon FSx for Windows File Server上运行的SQL Server。



=== 快速创建可用于PostgreSQL服务器部署

您可以使用此快速部署选项创建具有HA配置和嵌入式最佳实践的PostgreSQL服务器。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["在BlueXP  工作负载工厂中创建PostgreSQL服务器"]
