= 适用于所有 FSx for ONTAP 系统的全新架构良好的仪表板
:allow-uri-read: 




[[new-well-architected-dashboard-available-for-all-fsx-for-ontap-systems]]
=== 适用于所有 FSx for ONTAP 系统的全新架构良好的仪表板

现在，可以从 NetApp Workload Factory 中新的架构完善仪表板对 FSx for ONTAP 文件系统进行架构完善分析。新仪表板在一个位置集中显示跨帐户和区域的所有文件系统及其配置。当您从文件系统访问*架构完善*选项卡时，会出现弹出通知。在 Workload Factory 的左侧导航菜单中选择*架构完善*，即可访问新仪表板。

您仍然可以访问特定文件系统的良好架构分析，也可以通过 Storage 中的 *Well-architected* 菜单选项进行访问。



[[new-widgets-added-to-the-storage-dashboard]]
=== 新小部件已添加到存储仪表板

存储控制面板现在包括两个新的小部件，可帮助您了解如何使用存储空间并找到优化存储空间的方法。

* *Top discovered workloads* 显示标记服务在整个环境中找到的工作负载数据。查看置信度得分高于 80% 的工作负载，其中包括相关的 FSx 资源，例如卷和块设备。每个工作负载都显示其名称、资源数量、已调配容量和已用容量。按资源计数（默认值）、已调配容量或已用容量排序，以快速识别最大工作负载并了解存储使用模式。
* *AI 驱动的洞察与观察* 显示您托管资产的 AI 生成洞察。该小工具会在选定范围内查看您的资产数据，并突出显示关键领域的前三大发现，包括容量、性能、数据保护、复制、成本节约和存储趋势。


每个见解都包括摘要、详细调查结果和建议操作。展开见解以查看更多详细信息，并根据严重程度、性能改进和节省成本的机会排定问题的优先级。



[[workload-tagging]]
=== 工作负载标记



==== AWS Systems Manager 集成，用于工作负载标记

工作负载标记服务现在可与 AWS Systems Manager 配合使用，为主机库存数据添加更多详细信息。Workload Factory 现在可以收集和处理 SSM 库存信息，以更好地识别和分类工作负载。AWS SSM 属性也包含在标记过程中，以提高工作负载发现的准确性。

精心设计的仪表板中的每个卷相关配置现在都包含资源表中的 *Workload* 列。此列显示 Workload Factory 与每个卷关联的工作负载。



[[workload-tagging-and-ai-features]]
=== 工作负载标记和人工智能功能

当管理员禁用 AI 功能时，不会标记工作负载。如果在 Workload Factory 帐户设置中关闭了 AI 功能，则标记服务将不会识别或分类存储资源上的工作负载。

link:https://docs.netapp.com/us-en/workload-setup-admin/manage-genai-features.html["了解 AI 管理"^]。



[[explore-savings-snapshot-calculation-improvement]]
=== 探索节省快照计算改进

探索节省功能现在使用一致的快照容量计算，因此 FSx for ONTAP 节省估算可正确考虑额外的快照容量池要求。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html["了解如何在 Amazon Elastic Block Store、FSx for Windows File Server 和 Elastic File System 上为您的存储环境节省成本。"]



==== 将复制延迟数据导出到CSV

现在，您可以将复制延迟数据导出为 CSV 文件，以便在电子表格中分析数据并与他人共享。



[[s3-access-point-events]]
=== S3 访问点事件

您现在可以按照设定的计划将 S3 访问点事件发送到 SNS 主题。每次更新都包含自上次更新以来发生的所有事件。

要设置 S3 事件的通知，link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-s3-access-points.html["编辑 S3 接入点"]并选择 *Journal table* 部分下的 *Send S3 events by SNS*。



[[ontap-features-displayed-in-volumes-explorer]]
=== 卷资源管理器中显示的 ONTAP 功能

卷资源管理器现在在卷表中包含 ONTAP 功能。这些功能可更详细地了解卷的配置和状态，例如保护范围、自主勒索软件保护 (ARP/AI) 状态、存储效率、分层策略和卷自动增长。
