= 精心设计的分析更新
:allow-uri-read: 




=== 精心设计的分析更新

Workload Factory 会分析您的 FSx for ONTAP文件系统，以识别以下配置：

* NetApp自主勒索软件防护 (ARP/AI) 已禁用（包括块设备）：检查块设备卷上的 ARP/AI 是否已禁用
* 缓存关系写入模式：检查写入模式是否最适合缓存卷工作负载。
* 删除不必要的备份：检查备份是否已过期或不再需要，以便删除以降低成本。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看 FSx for ONTAP文件系统的良好架构状态"]



=== 问我关于人工智能助手首页集成的问题

Workload Factory 控制台主页嵌入了 Ask me AI 助手，使您可以询问有关您自己的存储环境的问题，直接从您的环境中获取个性化见解，并参考以前的对话。您可以与“问我”进行交互，以了解您的工作负载、解决问题并了解更多关于工作负载工厂的信息——所有这些都无需离开控制台。



=== 在 Lambda 链接资源中采用 IAM 用户主体权限策略

用于连接 Workload Factory 帐户和一个或多个 FSx for ONTAP文件系统以执行高级ONTAP操作的 Lambda 链接，现在使用 IAM 用户主体进行基于资源的策略权限。此项变更使 AWS 资源访问与行业最佳实践更加一致。



=== 为 EMS 事件的 AI 分析器添加了分析屏幕

存储菜单中新增了“分析”屏幕。从此屏幕，您可以使用适用于ONTAP EMS 事件功能的 FSx AI 分析器。



=== NetApp Workload Factory中的块设备增强功能

针对块设备进行了以下增强。



==== 创建块设备

NetApp Workload Factory支持在 FSx for ONTAP文件系统上使用 iSCSI 协议创建块设备，以便您可以从 Workload Factory 控制台更好地支持您的业务线 (LOB) 应用程序。



==== 块设备管理增强功能

NetApp Workload Factory包含以下增强功能： link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["管理块设备"]。您现在可以从 Workload Factory 控制台执行以下任务：

* 管理客户端访问权限
* 归档块设备数据
* 删除块设备




==== 支持包含块设备的FlexVol卷上的 ARP/AI

您可以启用 link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["NetApp自主勒索软件防护（AI 防护，ARP/AI）"] 在包含块设备的FlexVol卷上。启用 ARP/AI 可以利用人工智能检测勒索软件攻击，并有助于数据恢复。
